### ISSUE TITLE
Addon icon does not show in the toolbar, and is broken in the addons menu

### ISSUE THREAD

**Issue by sashaweiss** [natasha-codes/firefox-tab-islands#2]
Addon icon does not show up in the toolbar:
![image](https://user-images.githubusercontent.com/9013117/86506738-307db200-bd87-11ea-8fe7-7695b3b910c1.png)

Also, addon icon in `about:addons` is broken:
![image](https://user-images.githubusercontent.com/9013117/86506744-412e2800-bd87-11ea-82fc-f0a32d247a87.png)

**Comment by sashaweiss** [comment]
Also broken in the store:

![image](https://user-images.githubusercontent.com/9013117/86506806-c9acc880-bd87-11ea-9c2d-b493d21a2a6a.png)

**Comment by nathanshelly** [comment]
Toolbar button added in d61f5594a0a1e861ce31f8ae4570095ceb6a882a (opens settings page)
