### ISSUE TITLE
All islands have the same color and icon

### ISSUE THREAD

**Issue by sashaweiss** [natasha-codes/firefox-tab-islands#3]
All islands are assigned the same color and icon:

![image](https://user-images.githubusercontent.com/9013117/86506758-5dca6000-bd87-11ea-8890-a6cc4cd067d9.png)

![image](https://user-images.githubusercontent.com/9013117/86506763-628f1400-bd87-11ea-81f2-7f9929fa0129.png)

**Comment by nathanshelly** [comment]
closed by fcf91ee
